#version: '3.8'

services:

#  Database Container Configuration
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "SCD_Tema2_2024!"
      MSSQL_PID: "Developer"
    volumes:
      - tema2SCD_database_volume:/var/opt/mssql
    networks:
      - global-network

# Spring Server Configuration
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
      DATABASE_IP: database
      DATABASE_PORT: 1433
      DATABASE_USER: sa
      DATABASE_PASSWORD: SCD_Tema2_2024!
    depends_on:
      - database
    networks:
      - global-network
    entrypoint: ["mvn", "spring-boot:run", "-DskipTests"]

# Volume is used to manage data consistency ofter restart
volumes:
  tema2SCD_database_volume:

# Global network use for containers
networks:
  global-network:
    driver: bridge
