spring:
  application:
    name: Tema2 SCD

#  Database security entry configuration
  datasource:
    url: jdbc:sqlserver://${DATABASE_IP:localhost}:${DATABASE_PORT:1433};encrypt=false;trustServerCertificate=true
    username: ${DATABASE_USER:sa}
    password: ${DATABASE_PASSWORD:SCD_Tema2_2024!}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

# Database interaction configuration
  jpa:
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    root: INFO
