spring:
  application:
    name: Tema2 SCD

#  Database security entry configuration
  datasource:
    url: jdbc:sqlserver://${DATABASE_IP}:${DATABASE_PORT};encrypt=false;trustServerCertificate=true
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

# Database interaction configuration
  jpa:
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true

server:
  port: ${SERVER_PORT}

logging:
  level:
    root: INFO
